#!/bin/bash

set -euo pipefail

ME=$(basename "$0")

log() {
  >&2 echo "${ME}: $*"
}

die() {
  log "$@"
  exit 1
}

if [ "$#" -eq 0 ]; then
  log "updating containers in the current directory..."
  docker compose pull
  docker compose up -d
else 
  for compose_file in "$@"; do
    log "updating ${compose_file}..."
    docker compose -f "$compose_file" pull
    docker compose -f "$compose_file" up -d
  done
fi

log "removing all dangling images..."
docker image prune -f
